### ISSUE TITLE
Do

### ISSUE THREAD

**Issue by Minhnhat45** [VMD121199/SoftwareEngineeringPRJ#1]
abc

**Comment by Minhnhat45** [comment]
123

**Comment by Minhnhat45** [comment]
@VMD121199 @Vuducbao913  mặt lìn

**Comment by anhptn99** [comment]
chào 3 cậu

**Comment by Minhnhat45** [comment]
chào cậu

**Comment by Minhnhat45** [comment]
> chào 3 cậu

reply này

**Comment by Minhnhat45** [comment]
oiạdsfọidsà

**Comment by Minhnhat45** [comment]
ctrl + enter để nhắn nhanh nha

**Comment by anhptn99** [comment]
Chúng mình làm 1 trang website như shopee và tiki hả, chúng mình có thể tạo n ra app không?
