### ISSUE TITLE
Hoàn thành database

### ISSUE THREAD

**Issue by VMD121199** [VMD121199/SoftwareEngineeringPRJ#4]

**Comment by Minhnhat45** [comment]
cập nhật tình hình làm database đi các cậu

**Comment by anhptn99** [comment]
![fee4b8262492c2cc9b83](https://user-images.githubusercontent.com/52684675/68954458-a2a08700-07f6-11ea-953c-08a4353c462a.jpg)
các cậu xem database mình vừa làm xong xem có vấn đề gì không, có mấy chỗ như chỗ phần search ấy có cần cho vào database ko, vì muốn người dùng có thể hiện lên lịch sử tìm kiếm., và phần địa chỉ không biết liên kết thế nào với phần thành phố quận huyện. mọi người cùng góp ý nhé.

**Comment by anhptn99** [comment]
tớ gửi MYSQL Workbench mn tải về xem cho chi tiết 


[dattawebshop.zip](https://github.com/VMD121199/SoftwareEngineeringPRJ/files/3852217/dattawebshop.zip)

**Comment by anhptn99** [comment]
đây là phần migrations mn xem database được chưa nhé

**Comment by anhptn99** [comment]
các cậu ơi t push phần migrations lên code ồi :3 có gì mọi ng pull lại xem nhé
