### ISSUE TITLE
Thiết Kế Giao Diện

### ISSUE THREAD

**Issue by anhptn99** [VMD121199/SoftwareEngineeringPRJ#5]

**Comment by anhptn99** [comment]
Mọi người ơi Ánh đang thiết kế giao diện Trang chủ, Đăng Nhập, Đăng Ký, Đăng Tin rồi. Ánh push code lên nhé, Với cả @VMD121199 Đức ơi làm phần Tìm Kiếm nhaa

**Comment by anhptn99** [comment]
Mọi Người owii Ánh push code mới lên rồi nháaa

**Comment by Minhnhat45** [comment]
dạ okey Ánh
